alias b='pbcopy'
alias c=clear
alias cdp='cdproject'
alias df='df -h'
alias ds='ds -sh'
alias du='du -h'
alias e2='workon exam2 && cd exam2'
alias fab='nocorrect fab'
alias ffind='nocorrect ffind'
alias gs='git status'
alias ga='git add'
alias gaa='git add -A'
alias gcv='git commit -v'
alias gba='git branch -a'
alias h='history'
alias ip='ipython'
alias ipn="ipython notebook --pprint --pylab inline"
alias ks=ls
alias ls='ls -G --color'
alias la='ls -la'
alias ll='ls -lG'
alias lls='ls'
alias mkae='make'
alias o='open'
alias oepn='open'
alias p='python'
alias pass='apg -m 20 -x 30 -n 1 | pbcopy'  # random password
alias pyclean='find . -name "*.pyc" -delete ; find . -name __pycache__ -exec rm -rf {} \; '
alias pyhton='python'
alias sl=ls
alias v='vim'
alias vm="tab-color 0 150 0; cd ~/vagrant/cms && vagrant up && vagrant ssh"
alias vmoerp="tab-color 200 0 100; cd ~/vagrant/openerp-debian && vagrant up && vagrant ssh"
alias wo='workon'
